# Generated by Django 3.0.6 on 2020-05-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblAccess_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('Code', models.CharField(max_length=300)),
                ('access_token', models.CharField(max_length=400)),
                ('githublogin', models.CharField(blank=True, max_length=200, null=True)),
                ('githubfullname', models.CharField(blank=True, max_length=200, null=True)),
                ('emailid', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('Company', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
