# Generated by Django 3.0.6 on 2020-05-17 14:05

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0002_tblaccess_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblWebhooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhooks', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
